version: "3.7"

services:
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=phpstorm
      PHP_XDEBUG_IDEKEY: "phpstorm"
      PHP_XDEBUG_START_WITH_REQUEST: 1
      PHP_XDEBUG_CLIENT_HOST: 172.19.0.1
