<?php

/**
* Implements hook_form_alter().
 */
function recetas_core_form_node_receta_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  //print_r($form);
  $form["title"]["widget"][0]["value"]["#title"] = t('Recipe Name');
  $form["title"]["widget"][0]["value"]["#description"] = t('The Name of the recipe');
  $form["title"]["widget"][0]["value"]["#states"] = [
    'visible' => [
      ':input[name="langcode[0][value]"]' => ['value' => 'es']
    ]
  ];
  $form["title"]["widget"][0]["value"]["#ajax"] = [
    'callback' => 'recetas_core_title_ajax_callback',
    'event' => 'focus',
  ];
  $form["#validate"][] = 'recetas_core_add_validate';
  $form["actions"]["submit"]["#submit"][2] = 'recetas_core_add_submit';

  $form['#attached']['library'][] = 'recetas_core/example';
  $form['#attached']['drupalSettings']['recetas_example'] = ['button_id' => '#edit-submit'];


  $form["field_ingredientes"]["widget"]["#ajax"] = [
    'callback' => 'recetas_core_ajax_callback',
    'wrapper' => 'edit-status-value',
    'effect' => 'fade',
    'method' => 'replace',
  ];
  return;
}

function recetas_core_add_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form_state->setError($form["title"]["widget"][0]["value"], 'No ha pasado la validacion ');
  return;
}


function recetas_core_add_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  return;
}

function recetas_core_title_ajax_callback($form, \Drupal\Core\Form\FormStateInterface $form_state){
  $response = new \Drupal\Core\Ajax\AjaxResponse();
  $p = [
    '#type' => 'html_tag',
    '#tag' => 'p',
    '#value' => 'hola',
  ];
  $response->addCommand(new \Drupal\recetas_core\Ajax\ShowCommand("#edit-preview"));
  $response->addCommand(new \Drupal\Core\Ajax\SettingsCommand(['recetas-example' => ['button_id' => '#edit-preview']]));
  return $response;
}

/**
 * Implements hook_theme().
 */
function recetas_core_theme($existing, $type, $theme, $path)
{
  return [
    'recetas_core_vars'=> [
      'variables' => ['forums' => NULL, 'parents' => NULL, 'tid' => NULL],
    ],
    'recetas_core'=> [
      'render element' =>'element',
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function recetas_core_preprocess_recetas_core_vars(&$variables )
{
  $variables['forums']= t("hello");
}
